// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20260616205532_product-seed")]
    partial class productseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            ImageUrl = "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600",
                            IsDeleted = false,
                            Price = 54999.99m,
                            ProductName = "Apple iPhone 15 Pro",
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
                            ImageUrl = "https://images.unsplash.com/photo-1706439136251-58636289fc12?w=600",
                            IsDeleted = false,
                            Price = 49999.99m,
                            ProductName = "Samsung Galaxy S24 Ultra",
                            Stock = 40
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum.",
                            ImageUrl = "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600",
                            IsDeleted = false,
                            Price = 8999.99m,
                            ProductName = "Sony WH-1000XM5 Kulaklık",
                            Stock = 75
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia.",
                            ImageUrl = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600",
                            IsDeleted = false,
                            Price = 74999.99m,
                            ProductName = "Apple MacBook Pro 14\"",
                            Stock = 20
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
                            ImageUrl = "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600",
                            IsDeleted = false,
                            Price = 2499.99m,
                            ProductName = "Logitech MX Master 3 Mouse",
                            Stock = 120
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut labore et dolore magnam aliquam quaerat voluptatem incididunt.",
                            ImageUrl = "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600",
                            IsDeleted = false,
                            Price = 34999.99m,
                            ProductName = "Samsung 4K OLED TV 55\"",
                            Stock = 15
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.",
                            ImageUrl = "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600",
                            IsDeleted = false,
                            Price = 42999.99m,
                            ProductName = "iPad Pro 12.9\" M4",
                            Stock = 30
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse.",
                            ImageUrl = "https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=600",
                            IsDeleted = false,
                            Price = 1899.99m,
                            ProductName = "Mechanical Gaming Klavye",
                            Stock = 90
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. At vero eos et accusamus et iusto odio dignissimos ducimus blanditiis.",
                            ImageUrl = "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600",
                            IsDeleted = false,
                            Price = 13999.99m,
                            ProductName = "GoPro Hero 12 Black",
                            Stock = 35
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus.",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600",
                            IsDeleted = false,
                            Price = 18499.99m,
                            ProductName = "Dell UltraSharp 27\" Monitör",
                            Stock = 25
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero tempore cum soluta nobis eligendi optio cumque nihil impedit.",
                            ImageUrl = "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600",
                            IsDeleted = false,
                            Price = 19999.99m,
                            ProductName = "Dyson V15 Detect Süpürge",
                            Stock = 18
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Itaque earum rerum hic tenetur a sapiente delectus ut aut reiciendis.",
                            ImageUrl = "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600",
                            IsDeleted = false,
                            Price = 64999.99m,
                            ProductName = "Nikon Z6 III Fotoğraf Makinesi",
                            Stock = 12
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quis nostrum exercitationem ullam corporis suscipit laboriosam nisi ut.",
                            ImageUrl = "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600",
                            IsDeleted = false,
                            Price = 14999.99m,
                            ProductName = "Apple Watch Series 9",
                            Stock = 60
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium.",
                            ImageUrl = "https://images.unsplash.com/photo-1585664811087-47f65abbad64?w=600",
                            IsDeleted = false,
                            Price = 4299.99m,
                            ProductName = "Philips Airfryer XXL",
                            Stock = 45
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit fugit.",
                            ImageUrl = "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600",
                            IsDeleted = false,
                            Price = 24999.99m,
                            ProductName = "PlayStation 5 Slim",
                            Stock = 22
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minima veniam quis nostrum exercitationem ullam corporis.",
                            ImageUrl = "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600",
                            IsDeleted = false,
                            Price = 6999.99m,
                            ProductName = "Bose SoundLink Max Hoparlör",
                            Stock = 55
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.",
                            ImageUrl = "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600",
                            IsDeleted = false,
                            Price = 38999.99m,
                            ProductName = "LG Gram 16 Laptop",
                            Stock = 28
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Et harum quidem rerum facilis est et expedita distinctio libero tempore.",
                            ImageUrl = "https://images.unsplash.com/photo-1589894404892-7310b92ea7a2?w=600",
                            IsDeleted = false,
                            Price = 9499.99m,
                            ProductName = "Xiaomi Robot Süpürge S20+",
                            Stock = 33
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Temporibus autem quibusdam et aut officiis debitis rerum necessitatibus saepe.",
                            ImageUrl = "https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?w=600",
                            IsDeleted = false,
                            Price = 29999.99m,
                            ProductName = "Canon EOS R50 Aynasız",
                            Stock = 17
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Itaque earum rerum hic tenetur a sapiente delectus ut aut reiciendis voluptatibus.",
                            ImageUrl = "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=600",
                            IsDeleted = false,
                            Price = 3799.99m,
                            ProductName = "Corsair RM1000x PSU",
                            Stock = 42
                        });
                });

            modelBuilder.Entity("Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<byte>("Rating")
                        .HasColumnType("smallint");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full access.",
                            IsDeleted = false,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Standard customer access.",
                            IsDeleted = false,
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "rJaJ4ickJwheNbnT4+i+2IyzQ0gotDuG/AWWytTG4nA=",
                            PhoneNumber = "5550000001",
                            RoleId = 1,
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hikmet@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "gxwjeSjmISvtqkRRpRSs4xdFYvZ2H2oVei/lCCs24vs=",
                            PhoneNumber = "5550000002",
                            RoleId = 2,
                            Username = "Hikmet Kütük"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "okan@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "gxwjeSjmISvtqkRRpRSs4xdFYvZ2H2oVei/lCCs24vs=",
                            PhoneNumber = "5550000003",
                            RoleId = 2,
                            Username = "Okan Demirkan"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "onur@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "gxwjeSjmISvtqkRRpRSs4xdFYvZ2H2oVei/lCCs24vs=",
                            PhoneNumber = "5550000004",
                            RoleId = 2,
                            Username = "Onur Demir"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mustafa@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "gxwjeSjmISvtqkRRpRSs4xdFYvZ2H2oVei/lCCs24vs=",
                            PhoneNumber = "5550000005",
                            RoleId = 2,
                            Username = "Mustafa Ardınç"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "kurtulus@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "gxwjeSjmISvtqkRRpRSs4xdFYvZ2H2oVei/lCCs24vs=",
                            PhoneNumber = "5550000006",
                            RoleId = 2,
                            Username = "Kurtuluş Tekeci"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "samet@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "gxwjeSjmISvtqkRRpRSs4xdFYvZ2H2oVei/lCCs24vs=",
                            PhoneNumber = "5550000007",
                            RoleId = 2,
                            Username = "Samet Can Bayraktar"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ebrar@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "gxwjeSjmISvtqkRRpRSs4xdFYvZ2H2oVei/lCCs24vs=",
                            PhoneNumber = "5550000008",
                            RoleId = 2,
                            Username = "Ebar Karabacak"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tugra@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "gxwjeSjmISvtqkRRpRSs4xdFYvZ2H2oVei/lCCs24vs=",
                            PhoneNumber = "5550000009",
                            RoleId = 2,
                            Username = "Tuğra Mert Nehir"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bayram@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "gxwjeSjmISvtqkRRpRSs4xdFYvZ2H2oVei/lCCs24vs=",
                            PhoneNumber = "5550000010",
                            RoleId = 2,
                            Username = "Bayram Furkan Korkmaz"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mustafakarabacak@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "gxwjeSjmISvtqkRRpRSs4xdFYvZ2H2oVei/lCCs24vs=",
                            PhoneNumber = "5550000011",
                            RoleId = 2,
                            Username = "Mustafa Karabacak"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "osman@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "gxwjeSjmISvtqkRRpRSs4xdFYvZ2H2oVei/lCCs24vs=",
                            PhoneNumber = "5550000012",
                            RoleId = 2,
                            Username = "Osman Korkmaz"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "kodal@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "gxwjeSjmISvtqkRRpRSs4xdFYvZ2H2oVei/lCCs24vs=",
                            PhoneNumber = "5550000013",
                            RoleId = 2,
                            Username = "Muhammet Kodal"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "çetin@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "gxwjeSjmISvtqkRRpRSs4xdFYvZ2H2oVei/lCCs24vs=",
                            PhoneNumber = "5550000014",
                            RoleId = 2,
                            Username = "Abdullah Çetin"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ismail@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "gxwjeSjmISvtqkRRpRSs4xdFYvZ2H2oVei/lCCs24vs=",
                            PhoneNumber = "5550000015",
                            RoleId = 2,
                            Username = "İsmail Sercen Öztürk"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "kemal@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "gxwjeSjmISvtqkRRpRSs4xdFYvZ2H2oVei/lCCs24vs=",
                            PhoneNumber = "5550000016",
                            RoleId = 2,
                            Username = "Kemal Ayhan"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "şükran@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "gxwjeSjmISvtqkRRpRSs4xdFYvZ2H2oVei/lCCs24vs=",
                            PhoneNumber = "5550000017",
                            RoleId = 2,
                            Username = "Şükran Kayabaşıoğlu"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "murat@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "gxwjeSjmISvtqkRRpRSs4xdFYvZ2H2oVei/lCCs24vs=",
                            PhoneNumber = "5550000018",
                            RoleId = 2,
                            Username = "Murat Salihoğlu"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "faik@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "gxwjeSjmISvtqkRRpRSs4xdFYvZ2H2oVei/lCCs24vs=",
                            PhoneNumber = "5550000019",
                            RoleId = 2,
                            Username = "Faik Emre Pusat"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ömer@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "gxwjeSjmISvtqkRRpRSs4xdFYvZ2H2oVei/lCCs24vs=",
                            PhoneNumber = "5550000020",
                            RoleId = 2,
                            Username = "Ömer Saroğlu"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Address", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.CartItem", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Review", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
